"""IRT Analysis — the psychometric method behind assessment scores.

A methodology demonstration: real assessment scaled scores come from Item
Response Theory, and this page fits a 2PL IRT model to the item-level responses
in the vendor feed, showing the estimated item parameters. Framed honestly — the
data is synthetic, so this demonstrates the *workflow*, not real-world insight.
"""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import analysis as A
import display as D

st.set_page_config(page_title="IRT Analysis — Ask the Data", page_icon="📐", layout="wide")

st.title("📐 IRT Analysis")
st.markdown(
    "Real assessment scaled scores aren't averages of raw marks — they come from "
    "**Item Response Theory**. This page fits a **2-parameter logistic (2PL)** "
    "IRT model to the item-level responses, estimating each item's *difficulty* "
    "and *discrimination* by marginal maximum likelihood (via the `girth` library)."
)

st.warning(
    "**This is a methodology demonstration, not an insight into the data.** "
    "The responses are synthetic, generated by a simple ability + noise model, "
    "so the fit recovers the shape of *that generator* — not any real-world "
    "truth. It shows the workflow you would run on real item responses.",
    icon="⚠️",
)

# --- pick response set (year level + domain) ---------------------------------

st.subheader("Choose the response set")
fits = A.available_fits()
years = sorted({yl for yl, _ in fits})
domains = sorted({d for _, d in fits})

c1, c2 = st.columns(2)
year_level = c1.selectbox("Year level", years, index=0)
domain = c2.selectbox("Domain (the response — its 0/1 item columns)", domains, index=0)

st.caption(
    "The **response** is the set of 0/1 item scores for this domain "
    "(e.g. `N3Q01`…). A student's latent ability is the covariate the model "
    "estimates; each item gets a difficulty and a discrimination."
)


@st.cache_data(show_spinner="Fitting the 2PL model…")
def _fit(year_level: int, domain: str):
    r = A.fit_2pl(year_level, domain)
    return r.items, r.n_persons, r.aic, r.bic


if st.button("Fit the 2PL model", type="primary"):
    items, n_persons, aic, bic = _fit(year_level, domain)

    st.subheader(f"Item parameters — Year {year_level} {domain}")
    st.caption(
        f"Fitted on {n_persons:,} students. **Difficulty**: where on the ability "
        "scale an item is hardest to discriminate (higher = harder). "
        "**Discrimination**: how sharply the item separates ability levels."
    )

    m1, m2, m3 = st.columns(3)
    m1.metric("Students", f"{n_persons:,}")
    m2.metric("AIC", f"{aic:,.0f}")
    m3.metric("BIC", f"{bic:,.0f}")

    left, right = st.columns([2, 3])
    with left:
        st.dataframe(
            items.rename(
                columns={
                    "item": "Item",
                    "difficulty": "Difficulty",
                    "discrimination": "Discrimination",
                }
            ),
            use_container_width=True,
            hide_index=True,
        )
    with right:
        # Difficulty per item, as a chart — sorted so it reads as a ranking.
        chart = items.set_index("item")[["difficulty"]].rename(
            columns={"difficulty": "Difficulty"}
        )
        st.bar_chart(chart.sort_values("Difficulty"), horizontal=True)

    st.caption(
        "Because every item in this synthetic domain has essentially the same "
        "generated difficulty, the estimates cluster — exactly what a correct "
        "fit should recover from this data. On real responses the parameters "
        "would spread, and this same workflow would reveal which items are hard "
        "and which discriminate well."
    )
