"""IRT analysis — a methodology demonstration.

Real NAPLAN scaled scores are produced by Item Response Theory (a Rasch / 2PL
model), not by averaging raw marks. This module fits a 2-parameter logistic
(2PL) IRT model to the item-level responses in the vendor feed and returns the
estimated item parameters — difficulty and discrimination.

**Honest framing.** The data here is synthetic, generated by a simple ability +
noise model. Fitting IRT to it recovers the shape of *that* generator, not any
real-world truth. This page is a demonstration of the *workflow and the method*
— the same steps you would run on real item responses — not a claim of insight
into the data. That distinction matters, and the page says so.

The heavy lifting is done by ``girth`` (a lightweight IRT library); this module
prepares the item-response matrix from the vendor CSVs and packages the result.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

import numpy as np
import pandas as pd

from emit_vendor import NOT_ATTEMPTED
from emit_warehouse import RAW_DIR

# A vendor item column: prefix (N/R/L), year level, question number.
_ITEM_RE = re.compile(r"^([NRL])(\d+)Q(\d+)$")

# Which prefix/question ranges belong to which domain (mirrors the reshape).
_SPELLING_Q = set(range(1, 7))
_GRAMMAR_Q = set(range(26, 32))

# Year levels available as vendor paper files.
YEAR_LEVELS = (3, 5, 7, 9)
# Domains with 0/1 item responses (Writing is criterion-scored, not item 0/1).
ITEM_DOMAINS = ("Numeracy", "Reading", "Spelling", "Grammar and Punctuation")


def _domain_of(column: str) -> str | None:
    match = _ITEM_RE.match(column)
    if not match:
        return None
    prefix, _year, question = match.group(1), match.group(2), int(match.group(3))
    if prefix == "N":
        return "Numeracy"
    if prefix == "R":
        return "Reading"
    if question in _SPELLING_Q:
        return "Spelling"
    if question in _GRAMMAR_Q:
        return "Grammar and Punctuation"
    return None


@dataclass(frozen=True)
class IRTResult:
    """Fitted 2PL item parameters plus fit statistics."""

    domain: str
    year_level: int
    items: pd.DataFrame       # columns: item, difficulty, discrimination
    ability: np.ndarray       # one estimated latent ability (theta) per student
    n_persons: int
    aic: float
    bic: float


def _response_matrix(year_level: int, domain: str) -> pd.DataFrame:
    """Persons x items 0/1 matrix for one (year level, domain).

    Reads the wide vendor file, selects the domain's item columns, recodes the
    'not attempted' sentinel to 0, and drops duplicate students. Rows are
    persons, columns are items — girth wants the transpose, handled at fit time.
    """
    vendor = pd.read_csv(RAW_DIR / f"vendor_y{year_level}.csv")
    vendor = vendor.drop_duplicates(subset="PlatformId")

    cols = [c for c in vendor.columns if _domain_of(c) == domain]
    matrix = vendor[cols].replace(NOT_ATTEMPTED, 0).astype(int)
    matrix.columns = cols
    return matrix.reset_index(drop=True)


def fit_2pl(year_level: int, domain: str) -> IRTResult:
    """Fit a 2PL IRT model to one (year level, domain)'s item responses.

    girth's ``twopl_mml`` estimates item difficulty and discrimination by
    marginal maximum likelihood. Input is items x persons (0/1); output carries
    the item parameters and AIC/BIC.
    """
    import girth

    responses = _response_matrix(year_level, domain)
    # girth wants items as rows, persons as columns.
    dataset = responses.to_numpy().T
    fit = girth.twopl_mml(dataset)

    items = pd.DataFrame(
        {
            "item": list(responses.columns),
            "difficulty": np.round(fit["Difficulty"], 3),
            "discrimination": np.round(fit["Discrimination"], 3),
        }
    )
    # Person ability (theta): the model's estimate of each student's latent
    # skill, recovered from their answer pattern alone. One value per student —
    # the person side of the IRT output, complementing the item side above.
    ability = np.asarray(fit["Ability"], dtype=float)

    return IRTResult(
        domain=domain,
        year_level=year_level,
        items=items,
        ability=ability,
        n_persons=responses.shape[0],
        # girth returns AIC/BIC as dicts keyed by 'final'/'null'/'delta'.
        aic=round(float(fit["AIC"]["final"]), 1),
        bic=round(float(fit["BIC"]["final"]), 1),
    )


def available_fits() -> list[tuple[int, str]]:
    """The (year level, domain) combinations the page can fit."""
    return [(yl, d) for yl in YEAR_LEVELS for d in ITEM_DOMAINS]


if __name__ == "__main__":
    result = fit_2pl(3, "Numeracy")
    print(f"2PL fit — Year {result.year_level} {result.domain} "
          f"({result.n_persons:,} students)")
    print("\nItem parameters:")
    print(result.items.to_string(index=False))
    ab = result.ability
    print(f"\nPerson ability (theta): {len(ab):,} students, "
          f"mean {ab.mean():.2f}, range {ab.min():.2f} to {ab.max():.2f}")
    print(f"\nAIC {result.aic}   BIC {result.bic}")
